import {
  AlertTriangleIcon,
  ArrowRight,
  BadgeCheck,
  BaggageClaim,
  Banknote,
  BanknoteArrowUp,
  Barcode,
  Bell,
  Boxes,
  ChartNoAxesCombined,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleDivide,
  CircleDollarSign,
  CircleHelp,
  CirclePercent,
  CircleUserRound,
  ClipboardList,
  ClipboardX,
  Clock3,
  Copy,
  CreditCard,
  Download,
  Ellipsis,
  File,
  FileSpreadsheet,
  FileText,
  FolderOpen,
  Globe2,
  GlobeCheck,
  Handbag,
  HandCoins,
  House,
  Info,
  Landmark,
  LayoutDashboard,
  ListFilter,
  LockKeyhole,
  LogOut,
  Mail,
  Medal,
  Menu,
  MonitorX,
  MoveRight,
  NotepadText,
  Package,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  Pencil,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Split,
  SquareTerminal,
  Star,
  Store,
  SummaryIcon,
  TargetIcon,
  Trash2,
  TriangleAlert,
  TrophyIcon,
  Upload,
  Users,
  Vault,
  Wallet,
  X,
} from 'lucide-react'
import type { LucideIcon, LucideProps } from 'lucide-react'

const icons = {
  'add-product': PackagePlus,
  'arrow-right': ArrowRight,
  'arrow-split': Split,
  analytics: ChartNoAxesCombined,
  average: CircleDivide,
  bank: Landmark,
  'banknote-arrow-up': BanknoteArrowUp,
  barcode: Barcode,
  'bulk-product': Boxes,
  card: CreditCard,
  'card-solid': CreditCard,
  cards: CreditCard,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'clipboard-close': ClipboardX,
  clock: Clock3,
  close: X,
  copy: Copy,
  'composite-product': PackageOpen,
  'doc-csv': FileSpreadsheet,
  'doc-pdf': FileText,
  'dollar-circle': CircleDollarSign,
  download: Download,
  edit: Pencil,
  ellipsis: Ellipsis,
  email: Mail,
  export: Upload,
  file: File,
  filter: ListFilter,
  'folder-open': FolderOpen,
  'global-search': Globe2,
  'globe-check': GlobeCheck,
  'hand-bag': Handbag,
  home: House,
  indicator: BadgeCheck,
  'info-circle': Info,
  landmark: Landmark,
  'layout-dashboard': LayoutDashboard,
  lock: LockKeyhole,
  'log-out': LogOut,
  'long-arrow-right': MoveRight,
  medal: Medal,
  menu: Menu,
  'menu-board': ClipboardList,
  moneys: Banknote,
  'monitor-x': MonitorX,
  naira: CircleDollarSign,
  note: NotepadText,
  notification: Bell,
  people: Users,
  'percentage-circle': CirclePercent,
  plus: Plus,
  printer: Printer,
  products: Boxes,
  receipt: Receipt,
  refresh: RefreshCw,
  sale: BaggageClaim,
  search: Search,
  setting: Settings,
  'shop-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'single-product': Package,
  star: Star,
  store: Store,
  strongbox: Vault,
  summary: SummaryIcon,
  target: TargetIcon,
  terminal: SquareTerminal,
  transaction: HandCoins,
  trash: Trash2,
  trophy: TrophyIcon,
  'user-circle': CircleUserRound,
  wallet: Wallet,
  warning: TriangleAlert,
  'alert-triangle-icon': AlertTriangleIcon,
  'shield-check': ShieldCheck,
  'package-search': PackageSearch,
}

type AppIconName = keyof typeof icons
interface AppIconProps extends Omit<LucideProps, 'name'> {
  name: AppIconName | (string & Record<never, never>)
  fallback?: LucideIcon
}

const AppIcon = ({ name, fallback: Fallback = CircleHelp, ...props }: AppIconProps) => {
  const Icon = icons[name as AppIconName] ?? Fallback
  return <Icon aria-hidden={props['aria-label'] ? undefined : true} {...props} />
}

export default AppIcon
export { icons }
export type { AppIconName, AppIconProps }
