name: Release SDK
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'How package version should be incremented?'
        required: true
        type: choice
        options:
          - prerelease
          - prepatch
          - premajor
          - patch
          - minor
          - major

permissions:
  actions: read
  checks: read
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: read
  pull-requests: read
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Production
    concurrency: Production

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Check project repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0 # Ensures full git history

      # Setup Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Read unreleased changelog
      - id: get-unreleased-changelog
        name: Get unreleased changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          operation: read

      # Verify that CHANGE.LOG has unreleased changes
      - name: Verify that CHANGELOG.md has unreleased changes
        run: |
          if [[ $(echo "$CHANGE_LOG" | wc -l) -le 1 ]]; then
            echo "No unreleased changes found in CHANGELOG.md"
            exit 1
          fi
        env:
          CHANGE_LOG: ${{ steps.get-unreleased-changelog.outputs.changelog }}

      # Get current package version
      - id: package-version
        name: Get current package version
        uses: martinbeentjes/npm-get-version-action@main

      # Bump package version
      - name: Bump release version
        run: |
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$(npm --no-git-tag-version version $RELEASE_TYPE)" >> $GITHUB_ENV
          echo "RELEASE_TAG=${{startsWith(github.event.inputs.release-type, 'pre') && 'beta' || 'latest' }}" >> $GITHUB_ENV
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}
          CURRENT_VERSION: ${{ steps.package-version.outputs.current-version}}

      # Manual approval for package release (issues)
      - name: Pending for approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 10
        with:
          secret: ${{ github.TOKEN }}
          approvers: abfatahi
          minimum-approvals: 1
          issue-title: 'Publishing savantlink-sdk: version will go from ${{ env.CURRENT_VERSION }} to ${{ env.NEW_VERSION }}'
        continue-on-error: false

      # Update changelog unreleased section with new version
      - name: Update changelog
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: release

      # Install dependencies required for prePublish script
      - name: Install required dependencies
        run: yarn install --frozen-lockfile

      # Lint
      - name: Run linting
        run: yarn lint

      # Build
      - name: Build
        run: yarn build

      # Setup git authentication
      - name: Setup git token
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Github Actions"
          email: ${{ secrets.DEVOPS_EMAIL }}

      # Commit changes
      - name: Commit CHANGELOG.md and package.json changes and create tag
        run: |
          git add "package.json"
          git add "CHANGELOG.md"
          git commit --no-verify -m "chore: release ${{ env.NEW_VERSION }}"
          git tag ${{ env.NEW_VERSION }}

      # Publish version to packages repository
      - name: Publish
        run: yarn publish --verbose --ignore-scripts --non-interactive --tag ${{ env.RELEASE_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SAVANTLINK_GITHUB_SDK_TOKEN }}

      # Push repository changes
      - name: Push changes to repository
        run: |
          git push --no-verify origin HEAD --tags

      # Read changelog content for release body
      - id: get-changelog-content
        name: Get version changelog content
        uses: superfaceai/release-changelog-action@v1
        with:
          path-to-changelog: CHANGELOG.md
          version: ${{ env.NEW_VERSION }}
          operation: read

      # Update Github release with changelog
      - name: Update Github release documentation
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          body: ${{ steps.get-changelog-content.outputs.changelog }}
          prerelease: ${{ startsWith(github.event.inputs.release-type, 'pre') }}
        env:
          GITHUB_TOKEN: ${{ secrets.SAVANTLINK_GITHUB_SDK_TOKEN }}
